name: Swift tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref || github.head_ref }}-macos
      cancel-in-progress: true
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v5
      - run: swift test --parallel --enable-code-coverage
