name: Swift tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-15
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref || github.head_ref }}-${{ matrix.os }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v5
      - run: swift test --parallel --enable-code-coverage
